name: renovate

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: renovatebot/github-action@v39.1.3


